import { Geist, Geist_Mono, Handlee } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"
import { Comic_Relief } from 'next/font/google';
import { SpeedInsights } from "@vercel/speed-insights/next"
import 'katex/dist/katex.min.css';

const fontC = Comic_Relief({
  subsets: ["latin"],
  weight:"400",
  variable: "--shadows"
})

const fontSub = Handlee({
  subsets: ["latin"],
  weight:"400",
  variable: "--hand"
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Science Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontC.variable} ${fontSub.variable}  antialiased bg-[#030712] font-main`}
      >
        <Analytics />
        <SpeedInsights />
        {children}
      </body>
    </html>
  );
}
